// @ts-nocheck
export * from "./contracts/index";
export * from "./contracts/openclaw";
export * from "./state/canvasStore";
export * from "./state/viewportStore";
export * from "./state/connectionStore";
export * from "./state/expansionStore";
export * from "./utils/camera";
export * from "./components/InfiniteViewport";
export * from "./components/ObjectRenderer";
export * from "./components/ConnectorLayer";
export * from "./components/CanvasShell";
export * from "./hooks/useCanvasClipboard";
export * from "./hooks/useAgentOnCanvas";
import { BlockRegistry } from "./contracts/BlockRegistry";
export { BlockRegistry };
import { NoteBlock } from "./components/blocks/NoteBlock";
import { RichTextBlock } from "./components/blocks/RichTextBlock";
import { AgentBlock } from "./components/blocks/AgentBlock";
import { GoalBlock } from "./components/blocks/GoalBlock";
import { ArtifactBlock } from "./components/blocks/ArtifactBlock";
import { ChatBlock } from "./components/blocks/ChatBlock";
import { MemoryClusterBlock } from "./components/blocks/MemoryClusterBlock";
import { AppBlock } from "./components/blocks/AppBlock";
// Register default blocks with both short and full IDs
BlockRegistry.register("note", NoteBlock);
BlockRegistry.register("iem.text.note", NoteBlock);
BlockRegistry.register("rich-text", RichTextBlock);
BlockRegistry.register("iem.text.rich", RichTextBlock);
BlockRegistry.register("agent", AgentBlock);
BlockRegistry.register("iem.agent.agent", AgentBlock);
BlockRegistry.register("iem.agent.researcher", AgentBlock);
BlockRegistry.register("iem.agent.builder", AgentBlock);
BlockRegistry.register("iem.agent.code", AgentBlock);
BlockRegistry.register("iem.agent.blank", AgentBlock);
BlockRegistry.register("goal", GoalBlock);
BlockRegistry.register("iem.intent.goal", GoalBlock);
BlockRegistry.register("artifact", ArtifactBlock);
BlockRegistry.register("iem.data.artifact", ArtifactBlock);
BlockRegistry.register("chat", ChatBlock);
BlockRegistry.register("iem.chat.chat", ChatBlock);
BlockRegistry.register("iem.chat.orchestrator", ChatBlock);
BlockRegistry.register("memory-cluster", MemoryClusterBlock);
BlockRegistry.register("iem.data.cluster", MemoryClusterBlock);
BlockRegistry.register("app", AppBlock);
BlockRegistry.register("iem.app.web", AppBlock);
BlockRegistry.register("iem.app.iframe", AppBlock);
export * from "./components/BlockLibraryDrawer";
export * from "./components/BlockLibraryCard";
export * from "./components/ImmersiveBlockModal";
export * from "./components/FloatingOrchestratorChat";
