import { blockRegistry } from "@iem/core";
import type { NodeCatalog, NodeCatalogEntry, Schema } from "./types";
import { z } from "zod";

const createEntry = (
  type: string,
  category: "creative" | "workflow",
  label: string,
  description: string,
  inputSchema: Schema,
  outputSchema: Schema,
  defaults: {
    inputs?: Record<string, unknown>;
    outputs?: Record<string, unknown>;
    config?: Record<string, unknown>;
  } = {},
  role?: "trigger" | "action" | "tool",
): NodeCatalogEntry => ({
  category,
  role,
  inputSchema,
  outputSchema,
  defaultData: {
    id: "",
    type,
    label,
    description,
    inputs: defaults.inputs ?? {},
    outputs: defaults.outputs ?? {},
    config: defaults.config ?? {},
    metadata: { category, label, description },
  },
});

// Helper to convert Zod schema to our simplified Schema type
function zodToSimpleSchema(zodSchema: any): Schema {
  if (!zodSchema || !(zodSchema instanceof z.ZodObject)) {
    return {};
  }

  const shape = zodSchema.shape;
  const simple: Schema = {};

  for (const [key, value] of Object.entries(shape)) {
    if (value instanceof z.ZodString) simple[key] = "text";
    else if (value instanceof z.ZodNumber) simple[key] = "number";
    else if (value instanceof z.ZodBoolean) simple[key] = "boolean";
    else if (value instanceof z.ZodArray) simple[key] = "json";
    else if (value instanceof z.ZodRecord) simple[key] = "json";
    else simple[key] = "any";
  }

  return simple;
}

const BASE_CATALOG: NodeCatalog = {
  refiner: createEntry(
    "refiner",
    "creative",
    "Refiner",
    "Refine text into a specific writing style.",
    { source: ["text"] },
    { refined: "text" },
    {
      inputs: { source: "" },
      outputs: { refined: "" },
      config: { style: "Formal", additionalInstructions: "" },
    },
    "tool",
  ),
  summarizer: createEntry(
    "summarizer",
    "creative",
    "Summarizer",
    "Summarize and analyze mixed media inputs.",
    { sources: ["text", "audio", "image"] },
    { summary: "text", analysis: "text" },
    {
      inputs: { sources: [""] },
      outputs: { summary: "", analysis: "" },
      config: { additionalInstructions: "" },
    },
    "tool",
  ),
  translator: createEntry(
    "translator",
    "creative",
    "Translator",
    "Translate text/audio to a target language.",
    {
      source: ["text", "audio"],
      targetLanguage: "language",
      outputType: ["text", "audio"],
    },
    { result: ["text", "audio"], detectedLanguage: "text" },
    {
      inputs: { source: "", targetLanguage: "Spanish", outputType: "text" },
      outputs: { result: "", detectedLanguage: "" },
      config: { additionalInstructions: "" },
    },
    "tool",
  ),
  colorSwapper: createEntry(
    "colorSwapper",
    "creative",
    "Color Swapper",
    "Transfer palette from one image to another.",
    { imagePrimary: "image", imagePaletteSource: "image" },
    { image: "image" },
    {
      inputs: { imagePrimary: "", imagePaletteSource: "" },
      config: { additionalInstructions: "" },
    },
    "tool",
  ),
  filter: createEntry(
    "filter",
    "creative",
    "Filter",
    "Filter text or JSON with custom conditions.",
    { source: ["text", "json"], conditions: "text" },
    { filtered: ["text", "json"] },
    {
      inputs: { source: "", conditions: "" },
      config: { additionalInstructions: "" },
    },
    "tool",
  ),
  webScraper: createEntry(
    "webScraper",
    "creative",
    "Web Scraper",
    "Scrape a manually entered URL and return both structured JSON and plain text.",
    { url: "text" },
    { summary: "json", text: "text" },
    {
      inputs: { url: "https://" },
      outputs: { summary: {}, text: "" },
      config: {},
    },
    "tool",
  ),
  formatter: createEntry(
    "formatter",
    "creative",
    "Formatter",
    "Reformat files into requested output format.",
    { file: "file", desiredFormat: "text" },
    { formattedFile: "file" },
    {
      inputs: { file: "", desiredFormat: "json" },
      config: { additionalInstructions: "" },
    },
    "tool",
  ),
  programmer: createEntry(
    "programmer",
    "creative",
    "Programmer",
    "Generate code from prompt and optional source code.",
    { code: "code", prompt: "text" },
    { generatedCode: "code" },
    {
      inputs: { code: "", prompt: "" },
      config: { additionalInstructions: "" },
    },
    "tool",
  ),

  // --- Scribe Surface ---
  "scribe.prose": createEntry(
    "scribe.prose",
    "creative",
    "Prose",
    "Generate high-quality prose.",
    { payload: "text" },
    { success: "boolean", text: "text" },
    {},
    "tool",
  ),
  "scribe.chapter": createEntry(
    "scribe.chapter",
    "creative",
    "Chapter",
    "Draft an entire story chapter.",
    { title: "text", outline: "text" },
    { chapterContent: "text" },
    {},
    "tool",
  ),
  "scribe.characterProfile": createEntry(
    "scribe.characterProfile",
    "creative",
    "Character Profile",
    "Develop deep character bios.",
    { name: "text", traits: "text" },
    { profile: "json" },
    {},
    "tool",
  ),
  "scribe.worldLore": createEntry(
    "scribe.worldLore",
    "creative",
    "World Lore",
    "Build immersive world history and rules.",
    { topic: "text" },
    { lore: "text" },
    {},
    "tool",
  ),
  "scribe.dialogueTree": createEntry(
    "scribe.dialogueTree",
    "creative",
    "Dialogue Tree",
    "Branching conversation logic.",
    { actors: "json", premise: "text" },
    { tree: "json" },
    {},
    "tool",
  ),
  "scribe.editor": createEntry(
    "scribe.editor",
    "creative",
    "Editor",
    "Refine and critique writing.",
    { payload: "text" },
    { success: "boolean", text: "text" },
    {},
    "tool",
  ),
  "scribe.proofreader": createEntry(
    "scribe.proofreader",
    "creative",
    "Proofreader",
    "Correct grammar and spelling.",
    { text: "text" },
    { correctedText: "text" },
    {},
    "tool",
  ),

  // --- Playable Surface ---
  "playable.joystick": createEntry(
    "playable.joystick",
    "creative",
    "Joystick",
    "Input control for entities.",
    {},
    { direction: "vector2" },
    {},
    "tool",
  ),
  "playable.collider": createEntry(
    "playable.collider",
    "creative",
    "Collider",
    "Physics collision logic.",
    { targetA: "entity", targetB: "entity" },
    { onCollide: "trigger" },
    {},
    "tool",
  ),
  "playable.score": createEntry(
    "playable.score",
    "creative",
    "Score",
    "Manage game scoring.",
    { points: "number" },
    { currentScore: "number" },
    {},
    "tool",
  ),
  "playable.spawner": createEntry(
    "playable.spawner",
    "creative",
    "Spawner",
    "Entity spawning factory.",
    { entityType: "text", rate: "number" },
    { entity: "entity" },
    {},
    "tool",
  ),
  "playable.timer": createEntry(
    "playable.timer",
    "creative",
    "Timer",
    "Countdown and event timing.",
    { duration: "number" },
    { onComplete: "trigger" },
    {},
    "tool",
  ),
  "playable.sprite": createEntry(
    "playable.sprite",
    "creative",
    "Sprite",
    "Visual game entity representation.",
    { asset: "image" },
    { entity: "entity" },
    {},
    "tool",
  ),
  "playable.physicsEntity": createEntry(
    "playable.physicsEntity",
    "creative",
    "Physics Entity",
    "Rigid body physics object.",
    { mass: "number" },
    { state: "json" },
    {},
    "tool",
  ),

  // --- Atlas Surface ---
  "atlas.documentLoader": createEntry(
    "atlas.documentLoader",
    "creative",
    "Document Loader",
    "Load data from external files.",
    { url: "text" },
    { rawData: "text" },
    {},
    "tool",
  ),
  "atlas.chunker": createEntry(
    "atlas.chunker",
    "creative",
    "Chunker",
    "Split text for vector indexing.",
    { text: "text" },
    { chunks: "json" },
    {},
    "tool",
  ),
  "atlas.vectorSearch": createEntry(
    "atlas.vectorSearch",
    "creative",
    "Vector Search",
    "Semantic search across embeddings.",
    { query: "text" },
    { matches: "json" },
    {},
    "tool",
  ),
  "atlas.graphKnowledge": createEntry(
    "atlas.graphKnowledge",
    "creative",
    "Graph Knowledge",
    "Manage structured entity relations.",
    { entity: "text" },
    { relations: "json" },
    {},
    "tool",
  ),
  "atlas.indexer": createEntry(
    "atlas.indexer",
    "creative",
    "Indexer",
    "Index chunks into vector store.",
    { chunks: "json" },
    { success: "boolean" },
    {},
    "tool",
  ),
  "atlas.semanticRouter": createEntry(
    "atlas.semanticRouter",
    "creative",
    "Semantic Router",
    "Route intent based on semantics.",
    { input: "text" },
    { route: "text" },
    {},
    "tool",
  ),

  // --- Reel Surface ---
  "reel.forge": createEntry(
    "reel.forge",
    "creative",
    "Reel Forge",
    "Forge a playable video from connected reference images via Google Veo.",
    { prompt: "text" },
    { clipUrl: "text" },
    { inputs: { prompt: "" } },
    "tool",
  ),
  "reel.textToImage": createEntry(
    "reel.textToImage",
    "creative",
    "Text to Image",
    "Generate a reference still for the reel forge.",
    { prompt: "text" },
    { imageUrl: "text" },
    { inputs: { prompt: "" } },
    "tool",
  ),
  "reel.timeline": createEntry(
    "reel.timeline",
    "creative",
    "Timeline",
    "Sequence video events.",
    { events: "json" },
    { output: "video" },
    {},
    "tool",
  ),
  "reel.export": createEntry(
    "reel.export",
    "creative",
    "Export",
    "Final render and export pipeline.",
    { format: "text" },
    { fileUrl: "text" },
    {},
    "tool",
  ),
  "reel.scene": createEntry(
    "reel.scene",
    "creative",
    "Scene",
    "Define visual environment.",
    { description: "text" },
    { sceneData: "json" },
    {},
    "tool",
  ),
  "reel.character": createEntry(
    "reel.character",
    "creative",
    "Character",
    "Visual character in scene.",
    { profile: "json" },
    { entity: "entity" },
    {},
    "tool",
  ),
  "reel.transition": createEntry(
    "reel.transition",
    "creative",
    "Transition",
    "Visual scene transitions.",
    { type: "text" },
    { success: "boolean" },
    {},
    "tool",
  ),
  "reel.vfx": createEntry(
    "reel.vfx",
    "creative",
    "VFX",
    "Visual effect overlay.",
    { effect: "text" },
    { success: "boolean" },
    {},
    "tool",
  ),

  // --- Forge Surface ---
  "forge.architect": createEntry(
    "forge.architect",
    "creative",
    "Architect",
    "Design system infrastructure.",
    { goal: "text" },
    { specs: "json" },
    {},
    "tool",
  ),
  "forge.designer": createEntry(
    "forge.designer",
    "creative",
    "Designer",
    "UX and visual aesthetics.",
    { requirements: "text" },
    { assets: "json" },
    {},
    "tool",
  ),
  "forge.builder": createEntry(
    "forge.builder",
    "creative",
    "Builder",
    "Construct executable artifacts.",
    { specs: "json" },
    { code: "text" },
    {},
    "tool",
  ),
  "forge.tester": createEntry(
    "forge.tester",
    "creative",
    "Tester",
    "Automated verification agent.",
    { code: "text" },
    { results: "json" },
    {},
    "tool",
  ),

  // --- Conductor (Orchestration) ---
  "conductor.saas": createEntry(
    "conductor.saas",
    "creative",
    "SaaS Integration",
    "Connect to external APIs.",
    { provider: "text" },
    { data: "json" },
    {},
    "tool",
  ),
  "conductor.agent": createEntry(
    "conductor.agent",
    "creative",
    "Sub-Agent",
    "Autonomous worker node.",
    { instructions: "text" },
    { output: "text" },
    {},
    "tool",
  ),
  "conductor.router": createEntry(
    "conductor.router",
    "creative",
    "Router",
    "Logic branching path.",
    { condition: "text" },
    { path: "text" },
    {},
    "tool",
  ),
  "conductor.forEach": createEntry(
    "conductor.forEach",
    "creative",
    "For Each",
    "Iterate over collection.",
    { items: "json" },
    { item: "json" },
    {},
    "tool",
  ),
  "conductor.delay": createEntry(
    "conductor.delay",
    "creative",
    "Delay",
    "Wait for specified duration.",
    { ms: "number" },
    { onResume: "trigger" },
    {},
    "tool",
  ),
  "conductor.webhook": createEntry(
    "conductor.webhook",
    "creative",
    "Webhook",
    "Incoming external trigger.",
    {},
    { payload: "json" },
    {},
    "trigger",
  ),
  "conductor.state": createEntry(
    "conductor.state",
    "creative",
    "State",
    "Managed variable state.",
    { key: "text", value: "any" },
    { current: "any" },
    {},
    "tool",
  ),
  "conductor.errorBoundary": createEntry(
    "conductor.errorBoundary",
    "creative",
    "Error Boundary",
    "Graceful error recovery.",
    { node: "text" },
    { error: "json" },
    {},
    "tool",
  ),
  "conductor.subGraph": createEntry(
    "conductor.subGraph",
    "creative",
    "Sub-Graph",
    "Encapsulated logic group.",
    { graphId: "text" },
    { result: "any" },
    {},
    "tool",
  ),

  fileUpload: createEntry(
    "fileUpload",
    "creative",
    "Upload Node",
    "Represents an uploaded text/JSON/image file for downstream nodes.",
    {},
    { file: "file", text: "text", json: "json", image: "image" },
    {
      inputs: {
        fileName: "",
        mimeType: "",
      },
      outputs: {
        file: {},
      },
    },
    "tool",
  ),

  "trigger.time": createEntry(
    "trigger.time",
    "workflow",
    "Time Trigger",
    "Emits payload from a cron-like schedule.",
    {},
    { payload: "trigger" },
    { config: { cron: "0 14 * * 2", timezone: "America/Los_Angeles" } },
    "trigger",
  ),
  "trigger.webhook": createEntry(
    "trigger.webhook",
    "workflow",
    "Webhook Trigger",
    "Emits payload when webhook receives data.",
    {},
    { payload: "trigger" },
    { config: { path: "/hooks/main" } },
    "trigger",
  ),
  "trigger.slackMessage": createEntry(
    "trigger.slackMessage",
    "workflow",
    "Slack Message Trigger",
    "Emits payload when a Slack message event arrives.",
    {},
    { payload: "trigger", message: "message" },
    { config: { channel: "#general" } },
    "trigger",
  ),
  "trigger.calendlyEvent": createEntry(
    "trigger.calendlyEvent",
    "workflow",
    "Calendly Event Trigger",
    "Emits payload when a Calendly event is created.",
    {},
    { payload: "trigger", event: "json" },
    { config: { eventType: "30-min-intro" } },
    "trigger",
  ),

  "zoom.createMeeting": createEntry(
    "zoom.createMeeting",
    "workflow",
    "Zoom Create Meeting",
    "Create a Zoom meeting.",
    { payload: ["trigger", "json"], topic: "text", when: "text" },
    { meeting: "meeting" },
    { inputs: { topic: "Weekly Sync", when: "next Tuesday 2pm" } },
    "action",
  ),
  "zoom.getMeetingSummary": createEntry(
    "zoom.getMeetingSummary",
    "workflow",
    "Zoom Get Meeting Summary",
    "Retrieve meeting summary.",
    { payload: ["trigger", "json"], meetingId: "text" },
    { summary: "text", json: "json" },
    { inputs: { meetingId: "" } },
    "action",
  ),

  "discord.sendChannelMessage": createEntry(
    "discord.sendChannelMessage",
    "workflow",
    "Discord Send Channel Message",
    "Send a channel message.",
    {
      payload: ["trigger", "json", "text"],
      channelId: "text",
      message: "text",
    },
    { result: "json" },
    { inputs: { channelId: "", message: "" } },
    "action",
  ),
  "discord.sendDm": createEntry(
    "discord.sendDm",
    "workflow",
    "Discord Send DM",
    "Send a DM.",
    { payload: ["trigger", "json", "text"], userId: "text", message: "text" },
    { result: "json" },
    { inputs: { userId: "", message: "" } },
    "action",
  ),
  "discord.getChannelMessage": createEntry(
    "discord.getChannelMessage",
    "workflow",
    "Discord Retrieve Channel Message",
    "Get channel message by id.",
    { payload: ["trigger", "json"], channelId: "text", messageId: "text" },
    { message: "message", json: "json" },
    { inputs: { channelId: "", messageId: "" } },
    "action",
  ),

  "slack.inviteUserToChannel": createEntry(
    "slack.inviteUserToChannel",
    "workflow",
    "Slack Invite User to Channel",
    "Invite a user to a channel.",
    { payload: ["trigger", "json"], userId: "text", channelId: "text" },
    { result: "json", text: "text" },
    {
      inputs: { userId: "", channelId: "" },
      outputs: { result: {}, text: "" },
    },
    "action",
  ),
  "slack.sendChannelMessage": createEntry(
    "slack.sendChannelMessage",
    "workflow",
    "Slack Send Channel Message",
    "Send a Slack channel message.",
    {
      payload: ["trigger", "json", "text"],
      channelId: "text",
      message: "text",
    },
    { result: "json", text: "text" },
    {
      inputs: { channelId: "", message: "" },
      outputs: { result: {}, text: "" },
    },
    "action",
  ),
  "slack.sendDm": createEntry(
    "slack.sendDm",
    "workflow",
    "Slack Send DM",
    "Send a Slack direct message.",
    { payload: ["trigger", "json", "text"], userId: "text", message: "text" },
    { result: "json", text: "text" },
    { inputs: { userId: "", message: "" }, outputs: { result: {}, text: "" } },
    "action",
  ),
  "slack.getMessage": createEntry(
    "slack.getMessage",
    "workflow",
    "Slack Get Message",
    "Retrieve a Slack message by timestamp.",
    { payload: ["trigger", "json"], channelId: "text", messageTs: "text" },
    { message: "message", json: "json", text: "text" },
    {
      inputs: { channelId: "", messageTs: "" },
      outputs: { message: {}, json: {}, text: "" },
    },
    "action",
  ),
  "slack.readMessages": createEntry(
    "slack.readMessages",
    "workflow",
    "Slack Read Messages",
    "Read recent messages from a channel.",
    { payload: ["trigger", "json", "text"], channelId: "text", limit: "text" },
    { messages: "json", text: "text" },
    {
      inputs: { channelId: "", limit: "20" },
      outputs: { messages: [], text: "" },
    },
    "action",
  ),
  "slack.listChannels": createEntry(
    "slack.listChannels",
    "workflow",
    "Slack List Channels",
    "List channels in the connected workspace.",
    {},
    { channels: "json", text: "text" },
    { outputs: { channels: [], text: "" } },
    "action",
  ),
  "slack.listUsers": createEntry(
    "slack.listUsers",
    "workflow",
    "Slack List Users",
    "List users in the connected workspace.",
    {},
    { members: "json", text: "text" },
    { outputs: { members: [], text: "" } },
    "action",
  ),
  "slack.inviteUserToWorkspace": createEntry(
    "slack.inviteUserToWorkspace",
    "workflow",
    "Slack Invite User to Workspace",
    "Invite a user to the workspace (Enterprise Grid required).",
    { payload: ["trigger", "json"], email: "text", teamId: "text" },
    { result: "json", text: "text" },
    { inputs: { email: "", teamId: "" }, outputs: { result: {}, text: "" } },
    "action",
  ),
  "slack.createChannel": createEntry(
    "slack.createChannel",
    "workflow",
    "Slack Create Channel",
    "Create a new Slack channel.",
    { name: "text", is_private: "text" },
    { channel: "json", text: "text" },
    {
      inputs: { name: "", is_private: "false" },
      outputs: { channel: {}, text: "" },
    },
    "action",
  ),

  "trello.createBoard": createEntry(
    "trello.createBoard",
    "workflow",
    "Trello Create Board",
    "Create Trello board.",
    { payload: ["trigger", "json"], name: "text" },
    { board: "json" },
    { inputs: { name: "Sprint Board" } },
    "action",
  ),
  "trello.createCard": createEntry(
    "trello.createCard",
    "workflow",
    "Trello Create Card",
    "Create Trello card.",
    {
      payload: ["trigger", "json", "text"],
      listId: "text",
      title: "text",
      description: "text",
    },
    { card: "json" },
    { inputs: { listId: "", title: "", description: "" } },
    "action",
  ),
  "trello.updateCard": createEntry(
    "trello.updateCard",
    "workflow",
    "Trello Update Card",
    "Update Trello card.",
    {
      payload: ["trigger", "json", "text"],
      cardId: "text",
      title: "text",
      description: "text",
    },
    { card: "json" },
    { inputs: { cardId: "", title: "", description: "" } },
    "action",
  ),
  "trello.getCard": createEntry(
    "trello.getCard",
    "workflow",
    "Trello Get Card",
    "Fetch Trello card.",
    { payload: ["trigger", "json"], cardId: "text" },
    { card: "json" },
    { inputs: { cardId: "" } },
    "action",
  ),
  "trello.getBoard": createEntry(
    "trello.getBoard",
    "workflow",
    "Trello Get Board",
    "Fetch Trello board.",
    { payload: ["trigger", "json"], boardId: "text" },
    { board: "json" },
    { inputs: { boardId: "" } },
    "action",
  ),

  "calendly.sendInviteLink": createEntry(
    "calendly.sendInviteLink",
    "workflow",
    "Calendly Send Invite Link",
    "Send Calendly invite link.",
    { payload: ["trigger", "json", "text"], recipientEmail: "email" },
    { invite: "json" },
    { inputs: { recipientEmail: "" } },
    "action",
  ),
  "calendly.retrieveAvailability": createEntry(
    "calendly.retrieveAvailability",
    "workflow",
    "Calendly Retrieve Availability",
    "Get Calendly availability.",
    { payload: ["trigger", "json"], range: "text" },
    { availability: "json" },
    { inputs: { range: "next 7 days" } },
    "action",
  ),

  "gmail.sendEmail": createEntry(
    "gmail.sendEmail",
    "workflow",
    "Gmail Send Email",
    "Send an email through the connected Gmail account.",
    {
      payload: ["trigger", "json", "text"],
      to: "email",
      subject: "text",
      body: "text",
    },
    { result: "json", text: "text" },
    {
      inputs: { to: "", subject: "", body: "" },
      outputs: { result: {}, text: "" },
    },
    "action",
  ),
  "gmail.retrieveEmail": createEntry(
    "gmail.retrieveEmail",
    "workflow",
    "Gmail Retrieve Email",
    "Retrieve emails by Gmail search query.",
    {
      payload: ["trigger", "json"],
      query: "text",
      maxResults: "text",
      includeSpamTrash: "text",
    },
    { email: "email", emails: "json", json: "json", text: "text" },
    {
      inputs: { query: "", maxResults: "10", includeSpamTrash: "false" },
      outputs: { email: {}, emails: [], json: {}, text: "" },
    },
    "action",
  ),

  "sheets.createSpreadsheet": createEntry(
    "sheets.createSpreadsheet",
    "workflow",
    "Google Sheets Create Spreadsheet",
    "Create spreadsheet.",
    { payload: ["trigger", "json"], title: "text" },
    { spreadsheet: "sheet" },
    { inputs: { title: "Automation Output" } },
    "action",
  ),
  "sheets.updateSpreadsheet": createEntry(
    "sheets.updateSpreadsheet",
    "workflow",
    "Google Sheets Update Spreadsheet",
    "Update spreadsheet.",
    {
      payload: ["trigger", "json"],
      spreadsheetId: "text",
      range: "text",
      values: "json",
    },
    { spreadsheet: "sheet", json: "json" },
    { inputs: { spreadsheetId: "", range: "A1", values: "[]" } },
    "action",
  ),
  "sheets.readSpreadsheet": createEntry(
    "sheets.readSpreadsheet",
    "workflow",
    "Google Sheets Read Spreadsheet",
    "Read spreadsheet.",
    { payload: ["trigger", "json"], spreadsheetId: "text", range: "text" },
    { rows: "json" },
    { inputs: { spreadsheetId: "", range: "A1:C20" } },
    "action",
  ),
};

export const NODE_CATALOG: NodeCatalog = { ...BASE_CATALOG };

// Dynamically populate from registry
export function refreshCatalogFromRegistry() {
  blockRegistry.list().forEach((block) => {
    if (!NODE_CATALOG[block.id]) {
      NODE_CATALOG[block.id] = {
        category: (block.category as "creative" | "workflow") || "creative",
        role: block.mode === "triggered" ? "action" : "tool",
        inputSchema: zodToSimpleSchema(block.input),
        outputSchema: zodToSimpleSchema(block.output),
        defaultData: {
          id: "",
          type: block.id,
          label: block.name,
          description: block.description,
          inputs: {},
          outputs: {},
          config: {},
          metadata: {
            category: (block.category || "creative") as "creative" | "workflow",
            label: block.name,
            description: block.description,
          },
        },
      };
    }
  });
}

// Initial sync
refreshCatalogFromRegistry();

export const CREATIVE_NODE_TYPES = Object.keys(NODE_CATALOG).filter(
  (type) => NODE_CATALOG[type]?.category === "creative",
);

export const WORKFLOW_NODE_TYPES = Object.keys(NODE_CATALOG).filter(
  (type) => NODE_CATALOG[type]?.category === "workflow",
);
