import { useState } from "react";
import { ReactFlow, Controls, Background } from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import { useWorkflowStore } from "./store";
import { Send, Play, Download, Bot, User, Code, FileText } from "lucide-react";

export default function WorkflowPage() {
  const {
    nodes,
    edges,
    setNodes,
    refineMessages,
    addRefineMessage,
    artifacts,
    addArtifact,
    clearArtifacts,
  } = useWorkflowStore();
  const [chatInput, setChatInput] = useState("");
  const [isRunning, setIsRunning] = useState(false);

  // Left Rail: Chat handling
  const handleSendChat = () => {
    if (!chatInput.trim()) return;
    addRefineMessage({ role: "user", content: chatInput });
    setChatInput("");

    // Mock Agent processing a graph change request
    setTimeout(() => {
      if (
        chatInput.toLowerCase().includes("add") ||
        chatInput.toLowerCase().includes("change")
      ) {
        addRefineMessage({
          role: "agent",
          content:
            "I have proposed a change to add a formatting step. I have updated the graph in the center. Let me know if it looks good!",
        });

        // Mutate the graph to simulate agent altering the workflow
        setNodes([
          {
            id: "1",
            type: "default",
            position: { x: 250, y: 50 },
            data: { label: "Input Configuration" },
          },
          {
            id: "2",
            type: "default",
            position: { x: 250, y: 150 },
            data: { label: "LLM Processing" },
          },
          {
            id: "2.5",
            type: "default",
            position: { x: 250, y: 250 },
            data: { label: "Format Output to JSON" },
          },
          {
            id: "3",
            type: "output",
            position: { x: 250, y: 350 },
            data: { label: "Output Generator" },
          },
        ]);
      } else {
        addRefineMessage({
          role: "agent",
          content:
            "Sounds good. When you are happy with the workflow, click Run in the top right.",
        });
      }
    }, 1500);
  };

  // Top Right: Run execution handling
  const handleRunWorkflow = () => {
    setIsRunning(true);
    clearArtifacts();

    // Mock execution cascade
    setTimeout(() => {
      setIsRunning(false);
      // Generate mock artifacts from the final node
      addArtifact({
        name: "main.py",
        type: "code",
        content: 'print("Hello World generated by Gemini!")\n',
      });
      addArtifact({
        name: "config.json",
        type: "json",
        content: '{\n  "version": "1.0",\n  "status": "success"\n}',
      });
    }, 2500);
  };

  // Download helper
  const downloadContent = (name: string, content: string) => {
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = name;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex h-screen w-full bg-brand-bg overflow-hidden">
      {/* Left Rail: Refinement Chat */}
      <div className="w-80 border-r border-white/10 bg-brand-surface flex flex-col z-10">
        <div className="p-4 border-b border-white/10 font-bold tracking-wider uppercase text-xs text-white/50">
          Workflow Copilot
        </div>
        <div className="flex-1 overflow-y-auto p-4 space-y-4 custom-scrollbar">
          {refineMessages.map((msg, i) => (
            <div
              key={i}
              className={`flex gap-3 ${msg.role === "user" ? "justify-end" : "justify-start"}`}
            >
              {msg.role === "agent" && (
                <div className="mt-1">
                  <Bot size={14} className="text-brand-purple" />
                </div>
              )}
              <div
                className={`p-3 rounded-xl text-sm ${msg.role === "user" ? "bg-brand-purple text-white" : "bg-white/5 border border-white/10 text-white/90"}`}
              >
                {msg.content}
              </div>
            </div>
          ))}
        </div>
        <div className="p-4 border-t border-white/10 relative">
          <input
            type="text"
            value={chatInput}
            onChange={(e) => setChatInput(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && handleSendChat()}
            placeholder="Change the workflow..."
            className="w-full bg-black/30 border border-white/10 rounded-lg px-4 py-3 text-sm outline-none focus:border-brand-purple transition-colors pr-10"
          />
          <button
            onClick={handleSendChat}
            className="absolute right-6 top-1/2 -translate-y-1/2 text-brand-purple hover:text-white transition-colors"
          >
            <Send size={16} />
          </button>
        </div>
      </div>

      {/* Center: Node Canvas */}
      <div className="flex-1 relative bg-brand-bg">
        <div className="absolute top-4 right-4 z-20">
          <button
            onClick={handleRunWorkflow}
            disabled={isRunning}
            className="flex items-center gap-2 px-6 py-3 rounded-xl bg-brand-cyan text-black font-black uppercase tracking-widest hover:bg-white transition-colors disabled:opacity-50"
          >
            {isRunning ? "Executing..." : "Run Workflow"}{" "}
            <Play size={16} fill="currentColor" />
          </button>
        </div>
        <ReactFlow nodes={nodes} edges={edges} fitView>
          <Background color="#ffffff" gap={24} size={1} opacity={0.05} />
          <Controls className="!bg-brand-surface !border-white/10 !fill-white" />
        </ReactFlow>
      </div>

      {/* Right Rail: Artifacts */}
      <div className="w-80 border-l border-white/10 bg-brand-surface flex flex-col z-10">
        <div className="p-4 border-b border-white/10 font-bold tracking-wider uppercase text-xs text-white/50">
          Generated Output
        </div>
        <div className="flex-1 p-4 overflow-y-auto space-y-3 custom-scrollbar">
          {artifacts.length === 0 ? (
            <div className="text-center text-white/30 text-sm mt-10">
              Run the workflow to generate files.
            </div>
          ) : (
            artifacts.map((art, i) => (
              <div
                key={i}
                className="p-3 rounded-xl bg-white/5 border border-white/10 flex items-center justify-between group"
              >
                <div className="flex items-center gap-3 overflow-hidden">
                  <div className="p-2 rounded-lg bg-white/10">
                    {art.type === "code" ? (
                      <Code size={14} className="text-brand-cyan" />
                    ) : (
                      <FileText size={14} className="text-brand-purple" />
                    )}
                  </div>
                  <span className="text-sm truncate">{art.name}</span>
                </div>
                <button
                  onClick={() => downloadContent(art.name, art.content)}
                  className="p-2 rounded-lg hover:bg-white/10 opacity-0 group-hover:opacity-100 transition-all text-white/60 hover:text-white"
                >
                  <Download size={14} />
                </button>
              </div>
            ))
          )}
        </div>
      </div>
    </div>
  );
}
